# Generated by Django 5.0.2 on 2024-02-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="사용자 아이디"
                    ),
                ),
                ("password", models.CharField(max_length=20, verbose_name="비밀번호")),
                ("name", models.CharField(max_length=20, verbose_name="이름")),
                ("user_tel", models.CharField(max_length=11, verbose_name="전화번호")),
                ("email", models.CharField(max_length=20, verbose_name="이메일")),
            ],
        ),
    ]
