# Generated by Django 5.0.2 on 2024-02-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="view",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
