# Generated by Django 5.0.2 on 2024-02-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="score",
            field=models.IntegerField(
                default=0, help_text="0~5사이 값으로 입력하세요", verbose_name="평점"
            ),
        ),
    ]
