# Generated by Django 5.0.2 on 2024-02-14 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_post_view"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="thumbnail",
        ),
    ]
