# Generated by Django 5.0.2 on 2024-02-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="글수정 시간"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성 일시"),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="글수정 시간"),
        ),
    ]
