# Generated by Django 5.0.2 on 2024-02-15 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_post_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="score",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
