# Generated by Django 5.0.2 on 2024-02-15 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0004_rename_user_post_user_id_alter_post_score"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
                verbose_name="사용자 아이디",
            ),
        ),
    ]
