# Generated by Django 5.0.2 on 2024-02-15 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0006_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user_id",
            new_name="user",
        ),
    ]
