# Generated by Django 5.0.2 on 2024-02-15 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0007_rename_user_id_post_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="user_id",
            new_name="user",
        ),
    ]
